---
cidr_networks: &cidr_networks
  container: 
  tunnel: 
  storage: 

used_ips:

global_overrides:
  cidr_networks: *cidr_networks
  internal_lb_vip_address: 
  external_lb_vip_address:
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - ceph-osd

###
### Infrastructure
########################## TO be filled#####################

_infrastructure_hosts: {}

# nova hypervisors
compute_hosts: {}

placement-infra_hosts: {}

# galera, memcache, rabbitmq, utility
shared-infra_hosts: {}
# ceph-mon containers
#ceph-mon_hosts: *infrastructure_hosts

# repository (apt cache, python packages, etc)
repo-infra_hosts: {}

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts: {}

# rsyslog server
log_hosts: {}

###
### OpenStack
###

# keystone
identity_hosts: {}

# cinder api services
storage-infra_hosts: {}

# cinder volume hosts (Ceph RBD-backed)
storage_hosts: {}

# glance
image_hosts: {}

# nova api, conductor, etc services
compute-infra_hosts: {}

# heat
orchestration_hosts: {}

# horizon
dashboard_hosts: 

# neutron server, agents (L3, etc)
network_hosts: 
# masakari-infra_hosts:
masakari-infra_hosts: {}

# masakari-Monitors
masakari-monitor_hosts: {}

# Grafana Hosts
grafana_hosts: {}
#  hyd-mg-controller3:
#    ip: 10.103.155.15
#  hyd-mg-controller4:
#    ip: 10.103.155.16


# Promethus Hosts
prometheus_hosts: {}
#  hyd-mg-controller3:
#    ip: 10.103.155.15
#  hyd-mg-controller4:
#    ip: 10.103.155.16

# Opensatck Expoter
openstack-exporter_hosts: {}
#  hyd-mg-controller4:
#    ip: 10.103.155.16
#  hyd-mg-controller5:
#    ip: 10.103.155.17

